version: '3'
services:
  app:
    build: ./
    restart: always
    networks:
      network:
        ipv4_address: 172.20.0.15
networks:
  network:
    name: nginx-proxy-manager_default
    external: true
